### ISSUE TITLE
Line break should be `\` not `#parbreak()`

### ISSUE THREAD

**Issue by cittadhammo** [LegNeato/mdbook-typst#11]
In a Markdown document, double space after a line means line break. At the moment, this is transformed into `#parbreak()`. 

The solution is to replace it by `\`

https://stackoverflow.com/questions/35177253/why-markdown-syntax-requires-two-spaces-before-n-to-make-a-paragraph-out-of-it

**Comment by LegNeato** [comment]
Relevant spec:

https://spec.commonmark.org/0.31.2/#hard-line-breaks

**Comment by LegNeato** [comment]
This will be fixed when I integrate a version of `pullup` with https://github.com/LegNeato/pullup/commit/491dc239a691e4e36bfc5043f533bca50964995c

**Comment by LegNeato** [comment]
This should now be fixed in the latest release.
