### ISSUE TITLE
Quote Attribution

### ISSUE THREAD

**Issue by cittadhammo** [LegNeato/mdbook-typst#12]
I really like the [quote attribution](https://typst.app/docs/reference/model/quote/) in typst.

Is there a way to get that from markdown?

like:

```
> This is a nice block quote
> with two lines
> 
> -- Don Juan
```

would give:

```
#quote(attribution: [Don Juan])[This is a nice block quote with two lines]
```

**Comment by LegNeato** [comment]
This isn't supported natively in Markdown, so you'd have to do some processing of the markdown input events and generate a `pullup` Typst event you output. Note that the typst output event supports it, you just can't get the input data from pure markdown as there is no standard: https://github.com/LegNeato/pullup/commit/da906a5c9669b50e4e27f6949f063c579ceccc0e.
