### ISSUE TITLE
I think this is a typo

### ISSUE THREAD

**Issue by plus7wist** [LegNeato/mdbook-typst#4]
https://github.com/LegNeato/mdbook-typst/blob/ccd90d0edcb5fad1eed8b4bf977124cbf009a60b/src/main.rs#L171C48-L171C57

This should be `heading_numbering` instead of `text_font`.

**Comment by LegNeato** [comment]
Yep! I'll fix it in the next couple of days. Thanks for the report 🤙

**Comment by LegNeato** [comment]
This is fixed, thanks!
