### ISSUE TITLE
What shoudl happen after `mdbook-typst` on command line? 

### ISSUE THREAD

**Issue by epogrebnyak** [LegNeato/mdbook-typst#7]
I install mdbook-typst with cargo but whn I type `mdbook-typst` on command line nothing happens, also neither `mdbook-typst --help`, nor `mdbook-typst --version` work. How can I make sure mdbook-typst is installed correctly and make it run?

**Comment by epogrebnyak** [comment]
When running `mdbook build` I get:

```
@epogrebnyak ➜ /workspaces/mlmw (main) $ bin/mdbook build
2024-05-05 14:29:05 [INFO] (mdbook::book): Book building has started
2024-05-05 14:29:05 [INFO] (mdbook::book): Running the html backend
2024-05-05 14:29:05 [INFO] (mdbook::book): Running the typst backend
2024-05-05 14:29:05 [INFO] (mdbook::renderer): Invoking the "typst" renderer
error: unexpected argument '-v' found

Usage: typst [OPTIONS] <COMMAND>

For more information, try '--help'.
2024-05-05 14:29:05 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2024-05-05 14:29:05 [ERROR] (mdbook::utils): Error: Rendering failed
2024-05-05 14:29:05 [ERROR] (mdbook::utils):    Caused By: The "typst" renderer failed
```

**Comment by LegNeato** [comment]
It should just silently write the file. Weird that your version of typst doesn't have -v. Can you give the output of --help? What version of typst do you have installed?

**Comment by epogrebnyak** [comment]
the typst version is:
```
typst --version
typst 0.11.0 (69dcc89d)
```

For  `mdbook-typst --help` and `mdbook-typst --version` there is no output, but I 'm not sure if the utility shoud run as standalone command-line or just expects something on sdtin.

```
mdbook --version
mdbook v0.4.37
```

`mdbook build`  builds the typst file, but fails to make a pdf because of `-v` flag

**Comment by LegNeato** [comment]
Sorry, I meant you typist version.

I realize what the problem is. There is no -v flag, I forgot I was running a patched typst cli that I patched to enable verbose output (hence the -v. I'll fix and cut another release tomorrow.

**Comment by LegNeato** [comment]
Sorry this took so long, it is fixed and a new release is out
