### ISSUE TITLE
Quotes don't get transform properly

### ISSUE THREAD

**Issue by cittadhammo** [LegNeato/mdbook-typst#9]
Quote don't get transform properly in my case:

I have

```
> test
> test
> test
```

quotes in my md file and they get render as:

```
#par()[test]
```

as all the regular paragraph in the output

PS: It took me some time to understand that you have to run the normal cli: `mdbook build` to have the desire output. I thought it was `mdbook-typst` command that would create the output. Maybe you can update your readme with more instruction.

Thank you very much,
Best Wishes

**Comment by LegNeato** [comment]
This should be fixed in the latest release, let me know if it is not!

**Comment by cittadhammo** [comment]
OK thank you very much, i will give it a try

**Comment by cittadhammo** [comment]
@LegNeato Yes I tested and it works well ;-)
